apiVersion: v1
kind: Service
metadata:
  name: servicio-pedido
spec:
  selector:
    app: servicio-pedido
  ports:
    - protocol: TCP
      port: 80        # Puerto de Kubernetes
      targetPort: 3001 # Puerto en el que el contenedor escucha
  type: ClusterIP
