apiVersion: v1
kind: Service
metadata:
  name: servicio-producto
spec:
  selector:
    app: servicio-producto
  ports:
    - protocol: TCP
      port: 80           # Este es el puerto del servicio de Kubernetes, accesible dentro del clúster
      targetPort: 3002   # El puerto donde el contenedor escucha
  type: ClusterIP        # Asegúrate de que sea ClusterIP
