apiVersion: v1
kind: Service
metadata:
  name: servicio-usuario
spec:
  selector:
    app: servicio-usuario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Puerto accesible desde fuera del clúster
  type: NodePort
