apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-usuario
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servicio-usuario
  template:
    metadata:
      labels:
        app: servicio-usuario
    spec:
      containers:
      - name: servicio-usuario
        image: bydogek18/servicio-usuario:latest
        ports:
        - containerPort: 80  
