 
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  USERNAME: bydogek18  # Reemplaza con tu usuario de Docker Hub
  KUBECONFIG_PATH: .kube/config

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar acceso a Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login $REGISTRY -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Construir y subir imágenes Docker
      - name: Build and push usuario
        run: |
          docker build -t $REGISTRY/${{ env.USERNAME }}/servicio-usuario:latest ./usuario
          docker push $REGISTRY/${{ env.USERNAME }}/servicio-usuario:latest

      - name: Build and push producto
        run: |
          docker build -t $REGISTRY/${{ env.USERNAME }}/servicio-producto:latest ./producto
          docker push $REGISTRY/${{ env.USERNAME }}/servicio-producto:latest

      - name: Build and push pedido
        run: |
          docker build -t $REGISTRY/${{ env.USERNAME }}/servicio-pedido:latest ./pedido
          docker push $REGISTRY/${{ env.USERNAME }}/servicio-pedido:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Desplegar servicios en Kubernetes
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./usuario/usuario-deployment.yaml
          kubectl apply -f ./usuario/usuario-service.yaml
          kubectl apply -f ./producto/producto-deployment.yaml
          kubectl apply -f ./producto/producto-service.yaml
          kubectl apply -f ./pedido/pedido-deployment.yaml
          kubectl apply -f ./pedido/pedido-service.yaml
